export default {
 GET_PROFILES_START: 'GET_PROFILES__START',
 GET_PROFILES_SUCCESS: 'GET_PROFILES_SUCCESS',
 GET_PROFILES_ERROR: 'GET_PROFILES_ERROR',
 RESET_PROFILES_STORE:'RESET_PROFILES_STORE'   

}